apiVersion: batch/v1
kind: Job
metadata:
  name: database-init-job
  namespace: ldap-jwt-app
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: db-init
        image: ldap-jwt-backend:latest
        imagePullPolicy: Never
        command: ["python", "apply_schema.py"]
        env:
        - name: DB_HOST
          value: "timescaledb-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "auth_metadata"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "auth_metadata_pass"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      restartPolicy: Never 