apiVersion: batch/v1
kind: Job
metadata:
  name: database-init-job
  namespace: ldap-jwt-app
  labels:
    app: database-init
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: database-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: database-init
        image: ldap-jwt-backend:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "timescaledb-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "auth_metadata"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        command: ["python", "/app/apply_schema.py"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 