---
# Persistent Volume for LDAP data (will retain your users)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-data-pv-fixed
  labels:
    type: ldap-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /host_mnt/c/ldap-data
    type: DirectoryOrCreate

---
# Persistent Volume for LDAP config (will retain configuration)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-config-pv-fixed
  labels:
    type: ldap-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /host_mnt/c/ldap-config
    type: DirectoryOrCreate

---
# Persistent Volume Claim for LDAP data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data-pvc
  namespace: ldap-jwt-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: ldap-data

---
# Persistent Volume Claim for LDAP config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config-pvc
  namespace: ldap-jwt-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: ldap-config 